### ISSUE TITLE
error when I added "-DFABM_ERSEM_BASE=/path/to/my/ersem/code"

### ISSUE THREAD

**Issue by chevyyang** [fabm-model/fabm#10] opened 2020-09-07 09:01 UTC
Hi, guys
I could excute "make install" sucessfully when I did not add "ersem"
like this:
cd $HOME/Code/fabm/src
mkdir build
cd build
cmake $HOME/Code/fabm/src -DFABM_HOST=fvcom -DCMAKE_Fortran_COMPILER=$(which mpif90)
make install
It is  ok!
however, i got error when I add  "-DFABM_ERSEM_BASE=/path/to/my/ersem/code"

like this 
cd $HOME/Code/fabm/src
mkdir build
cd build
cmake $HOME/Code/fabm/src -DFABM_HOST=fvcom -DFABM_ERSEM_BASE=$HOME/Code/ersem -DCMAKE_Fortran_COMPILER=$(which mpif90)
make install

ERROR
/ersem/src/benthic_column_dissolved_matter.F90(96): error #8486: There is no matching specific subroutine for this type bound generic subroutine call.   [REGISTER_STATE_DEPENDENCY]
         call self%register_state_dependency(self%id_layer,'layer','m','depth of bottom interface of final layer', &
-------------------^
compilation aborted for benthic_column_dissolved_matter.F90 (code 1)
make[3]: *** [models/ersem/src/CMakeFiles/fabm_models_ersem.dir/benthic_column_dissolved_matter.F90.o] Error 1
make[2]: *** [models/ersem/src/CMakeFiles/fabm_models_ersem.dir/benthic_column_dissolved_matter.F90.o.provides] Error 2
make[1]: *** [models/ersem/src/CMakeFiles/fabm_models_ersem.dir/all] Error 2
make: *** [all] Error 2

Thank you very much for your help in advance!

**Comment by jornbr** [comment] 2020-09-07 11:27
Duplicate of #9

**Closed by jornbr** 2020-09-07 11:27 UTC

**Comment by xieyihui** [comment] 2020-09-07 13:15
> 
> 
> Hi, guys
> I could excute "make install" sucessfully when I did not add "ersem"
> like this:
> cd $HOME/Code/fabm/src
> mkdir build
> cd build
> cmake $HOME/Code/fabm/src -DFABM_HOST=fvcom -DCMAKE_Fortran_COMPILER=$(which mpif90)
> make install
> It is ok!
> however, i got error when I add "-DFABM_ERSEM_BASE=/path/to/my/ersem/code"
> 
> like this
> cd $HOME/Code/fabm/src
> mkdir build
> cd build
> cmake $HOME/Code/fabm/src -DFABM_HOST=fvcom -DFABM_ERSEM_BASE=$HOME/Code/ersem -DCMAKE_Fortran_COMPILER=$(which mpif90)
> make install
> 
> ERROR
> /ersem/src/benthic_column_dissolved_matter.F90(96): error #8486: There is no matching specific subroutine for this type bound generic subroutine call. [REGISTER_STATE_DEPENDENCY]
> call self%register_state_dependency(self%id_layer,'layer','m','depth of bottom interface of final layer', &
> -------------------^
> compilation aborted for benthic_column_dissolved_matter.F90 (code 1)
> make[3]: *** [models/ersem/src/CMakeFiles/fabm_models_ersem.dir/benthic_column_dissolved_matter.F90.o] Error 1
> make[2]: *** [models/ersem/src/CMakeFiles/fabm_models_ersem.dir/benthic_column_dissolved_matter.F90.o.provides] Error 2
> make[1]: *** [models/ersem/src/CMakeFiles/fabm_models_ersem.dir/all] Error 2
> make: *** [all] Error 2
> 
> Thank you very much for your help in advance!

Can you give me the qq number? I also encountered this problem

**Comment by chevyyang** [comment] 2020-09-11 12:59
> > Hi, guys
> > I could excute "make install" sucessfully when I did not add "ersem"
> > like this:
> > cd $HOME/Code/fabm/src
> > mkdir build
> > cd build
> > cmake $HOME/Code/fabm/src -DFABM_HOST=fvcom -DCMAKE_Fortran_COMPILER=$(which mpif90)
> > make install
> > It is ok!
> > however, i got error when I add "-DFABM_ERSEM_BASE=/path/to/my/ersem/code"
> > like this
> > cd $HOME/Code/fabm/src
> > mkdir build
> > cd build
> > cmake $HOME/Code/fabm/src -DFABM_HOST=fvcom -DFABM_ERSEM_BASE=$HOME/Code/ersem -DCMAKE_Fortran_COMPILER=$(which mpif90)
> > make install
> > ERROR
> > /ersem/src/benthic_column_dissolved_matter.F90(96): error #8486: There is no matching specific subroutine for this type bound generic subroutine call. [REGISTER_STATE_DEPENDENCY]
> > call self%register_state_dependency(self%id_layer,'layer','m','depth of bottom interface of final layer', &
> > -------------------^
> > compilation aborted for benthic_column_dissolved_matter.F90 (code 1)
> > make[3]: *** [models/ersem/src/CMakeFiles/fabm_models_ersem.dir/benthic_column_dissolved_matter.F90.o] Error 1
> > make[2]: *** [models/ersem/src/CMakeFiles/fabm_models_ersem.dir/benthic_column_dissolved_matter.F90.o.provides] Error 2
> > make[1]: *** [models/ersem/src/CMakeFiles/fabm_models_ersem.dir/all] Error 2
> > make: *** [all] Error 2
> > Thank you very much for your help in advance!
> 
> Can you give me the qq number? I also encountered this problem

793473728
